image: fedora:latest

variables:
  DEPS_COMMON: git libtool make python3 python3-six redhat-rpm-config
               python3-pyparsing meson ninja-build gtk-doc glib2-devel
               gettext gettext-devel

  DEPS_FEDORA: zlib-devel openssl-devel intltool gtk3-devel
               gobject-introspection-devel cyrus-sasl-devel
               pulseaudio-libs-devel libjpeg-turbo-devel
               libacl-devel gstreamer1-devel gstreamer1-plugins-base-devel
               polkit-devel vala lz4-devel opus-devel pixman-devel
               libcacard-devel celt051-devel libphodav-devel usbutils
               usbredir-devel libusbx-devel libsoup-devel json-glib-devel

  DEPS_MINGW: mingw64-gcc mingw64-pkg-config mingw64-pixman mingw64-openssl
              mingw64-gtk3 mingw64-json-glib mingw64-opus
              mingw64-gstreamer1-plugins-base mingw64-gstreamer1-plugins-good

fedora-autotools:
  before_script:
    - dnf install -y $DEPS_COMMON $DEPS_FEDORA
    - git clone ${CI_REPOSITORY_URL/spice-gtk/spice-protocol}
    - (cd spice-protocol && ./autogen.sh --prefix=/usr && make install)

  script:
    # Run with default options
    - ./autogen.sh --enable-static
    - make -j4
    - make check
    # Run without features
    - git clean -xfd
    - ./autogen.sh --enable-static
          --enable-lz4=no
          --enable-webdav=no
          --with-sasl=no
          --with-coroutine=auto
          --enable-pulse=no
          --enable-smartcard=no
          --enable-usbredir=no
    - make -j4
    - make check

fedora-meson:
  before_script:
    - dnf install -y $DEPS_COMMON $DEPS_FEDORA
    - git clone ${CI_REPOSITORY_URL/spice-gtk/spice-protocol}
    - meson spice-protocol build-spice-protocol --prefix=/usr
    - ninja -C build-spice-protocol install

  script:
    - meson build-default || (cat build-default/meson-logs/meson-log.txt && exit 1)
    - ninja -C build-default
    - ninja -C build-default test || (cat build-default/meson-logs/testlog.txt && exit 1)

    - meson build-feat-disabled -Dauto_features=disabled || (cat build-feat-disabled/meson-logs/meson-log.txt && exit 1)
    - ninja -C build-feat-disabled
    - ninja -C build-feat-disabled test || (cat build-feat-disabled/meson-logs/testlog.txt && exit 1)

windows-autotools:
  before_script:
    - dnf install -y $DEPS_COMMON $DEPS_MINGW
    - git clone ${CI_REPOSITORY_URL/spice-gtk/spice-protocol}
    - (cd spice-protocol && autoreconf -if && mingw64-configure --prefix=/usr && make install)

  script:
    - NOCONFIGURE=yes ./autogen.sh
    - PYTHON=python3 mingw64-configure --enable-static
    - make -j4
