image: fedora:latest

variables:
  DEPS_COMMON: git libtool make python3 python3-six redhat-rpm-config
               python3-pyparsing meson ninja-build gtk-doc glib2-devel
               gettext gettext-devel

  DEPS_FEDORA: zlib-devel openssl-devel intltool gtk3-devel
               gobject-introspection-devel cyrus-sasl-devel
               pulseaudio-libs-devel libjpeg-turbo-devel
               libacl-devel gstreamer1-devel gstreamer1-plugins-base-devel
               polkit-devel vala lz4-devel opus-devel pixman-devel
               libcacard-devel celt051-devel libphodav-devel usbutils
               usbredir-devel libusbx-devel libsoup-devel json-glib-devel
               bzip2

  DEPS_MINGW: mingw64-gcc mingw64-pkg-config mingw64-pixman mingw64-openssl
              mingw64-gtk3 mingw64-json-glib mingw64-opus
              mingw64-gstreamer1-plugins-base mingw64-gstreamer1-plugins-good

fedora-autotools:
  artifacts:
    paths:
      - tests/*.log
    when: always
    expire_in: 1 week

  before_script:
    - dnf install -y $DEPS_COMMON $DEPS_FEDORA
    - git clone ${CI_REPOSITORY_URL/spice-gtk/spice-protocol}
    - (cd spice-protocol && ./autogen.sh --prefix=/usr && make install)

  script:
    - git clean -xfd
    - git submodule foreach --recursive git clean -xfd
    # Run with default options + out-of-tree
    - mkdir build
    - cd build
    - ../autogen.sh --enable-static
    - make -j4
    - make check
    - cd ..
    # Run dist, check we don't have -dirty in the build
    - git clean -xfd
    - git submodule foreach --recursive git clean -xfd
    - git reset --hard HEAD
    - ./autogen.sh --disable-dependency-tracking --enable-celt051
    - make gitignore
    - (cd subprojects/spice-common && make gitignore)
    - ./autogen.sh --disable-dependency-tracking --enable-celt051
    - if grep -q 'VERSION=.*-dirty' configure; then echo 'Version is dirty!'; false; fi
    - make -j4
    - make dist
    - test -e spice-gtk-*.tar.bz2
    - test \! -e spice-gtk-*-dirty.tar.bz2
    # Run without features
    - git clean -xfd
    - git submodule foreach --recursive git clean -xfd
    - ./autogen.sh --enable-static
          --enable-lz4=no
          --enable-webdav=no
          --with-sasl=no
          --with-coroutine=auto
          --enable-pulse=no
          --enable-smartcard=no
          --enable-usbredir=no
    - make -j4
    - make check

fedora-meson:
  artifacts:
    paths:
      - build-*/meson-logs/*.txt
    when: always
    expire_in: 1 week

  before_script:
    - dnf install -y $DEPS_COMMON $DEPS_FEDORA
    - git clone ${CI_REPOSITORY_URL/spice-gtk/spice-protocol}
    - meson --buildtype=release spice-protocol build-spice-protocol --prefix=/usr
    - ninja -C build-spice-protocol install

  script:
    - meson --buildtype=release build-default
    - ninja -C build-default
    - ninja -C build-default test

    - meson --buildtype=release build-feat-disabled -Dauto_features=disabled
    - ninja -C build-feat-disabled
    - ninja -C build-feat-disabled test

windows-autotools:
  before_script:
    - dnf install -y $DEPS_COMMON $DEPS_MINGW
    - git clone ${CI_REPOSITORY_URL/spice-gtk/spice-protocol}
    - (cd spice-protocol && autoreconf -if && mingw64-configure --prefix=/usr && make install)

  script:
    - NOCONFIGURE=yes ./autogen.sh
    - PYTHON=python3 mingw64-configure --enable-static
    - make -j4

windows-meson:
  artifacts:
    paths:
      - build-win64/meson-logs/*.txt
      - spice-protocol/build-spice-protocol/meson-logs/*.txt
    when: always
    expire_in: 1 week

  before_script:
    - dnf install -y $DEPS_COMMON $DEPS_MINGW
    - git clone ${CI_REPOSITORY_URL/spice-gtk/spice-protocol}
    - mkdir spice-protocol/build-spice-protocol && cd spice-protocol/build-spice-protocol
    - mingw64-meson --buildtype=release --prefix=/usr
    - ninja install

  script:
    - cd $CI_PROJECT_DIR
    - mkdir build-win64 && cd build-win64
    - mingw64-meson --buildtype=release -Dgtk_doc=disabled
    - ninja install
