image: fedora:latest

variables:
  DEPS: git libtool make python3 python3-six redhat-rpm-config
        python3-pyparsing meson ninja-build zlib-devel openssl-devel
        intltool gtk3-devel gtk-doc gobject-introspection-devel
        cyrus-sasl-devel pulseaudio-libs-devel libjpeg-turbo-devel
        libacl-devel gstreamer1-devel gstreamer1-plugins-base-devel
        polkit-devel vala lz4-devel opus-devel libgudev-devel
        pixman-devel libcacard-devel celt051-devel libphodav-devel
        usbutils usbredir-devel libusbx-devel libsoup-devel
        json-glib-devel

before_script:
  - dnf install -y $DEPS
  - git clone ${CI_REPOSITORY_URL/spice-gtk/spice-protocol}
  - (cd spice-protocol && ./autogen.sh --prefix=/usr && make install)

makecheck:
  script:
  - ./autogen.sh --enable-static
  - make -j4
  - make check

makecheck-meson:
  script:
  - meson build || (cat build/meson-logs/meson-log.txt && exit 1)
  - ninja -C build
  - (cd build && meson test) || (cat build/meson-logs/testlog.txt && exit 1)

makecheck_simple:
  script:
  - ./autogen.sh --enable-static
        --enable-lz4=no
        --enable-gstaudio=no
        --enable-gstvideo=no
        --enable-webdav=no
        --with-sasl=no
        --with-coroutine=auto
        --enable-pulse=no
        --enable-smartcard=no
        --enable-usbredir=no
        --enable-dbus=no
  - make -j4
  - make check

makecheck_simple-meson:
  script:
  - meson build -Dlz4=false
                -Dgstaudio=false
                -Dgstvideo=false
                -Dwebdav=false
                -Dsasl=false
                -Dpulse=false
                -Dsmartcard=false
                -Dusbredir=false
                -Ddbus=false || (cat build/meson-logs/meson-log.txt && exit 1)
  - ninja -C build
  - (cd build && meson test) || (cat build/meson-logs/testlog.txt && exit 1)
